apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: my-container
    image: alpine
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret"
      readOnly: true 
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
